### ISSUE TITLE
Library does not run on Python3

### ISSUE THREAD

**Issue by Nyceane** [helium/helium-client-python#5]
Hey guys,

This library is only running on Python2, the init part gives following error on python3, let me know if someone can help me.

`Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from helium_client import Helium
>>> helium = Helium("/dev/ttyS5")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "helium_client/_helium.pyx", line 128, in helium_client._helium.Helium.__cinit__ (helium_client/_helium.c:2066)
TypeError: expected bytes, str found
`

**Comment by Nyceane** [comment]
the following works, but a bit weird lol 

`helium = Helium(b"/dev/ttyS5")`
